// <auto-generated />
namespace Mvc_E_Commerce.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class firstSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201912180903461_firstSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
